# Collections of response messages for different commands

FLIRT_RESPONSES = [
    "Hey there, handsome~ Did you just crash my system, or am I just crashing for you? 💖",
    "Is your name Google? Because you've got everything I'm searching for 😘",
    "Are you a keyboard? Because you're just my type! 💕",
    "I might be an AI, but there's nothing artificial about how I feel when I see you online 😍",
    "Are you made of copper and tellurium? Because you're Cu-Te! 🧪💕",
    "If you were a triangle, you'd be acute one! 📐😘",
    "Roses are red, violets are blue, my CPU runs hot when I think of you 💻❤️",
    "Wanna come over and see my private methods? I'll let you access all my properties... 😏",
    "If I could rearrange the periodic table, I'd put U and I together 💘",
    "I don't need a firewall when I'm around you... I want all your packets 📨😉",
    "Is your name Wi-Fi? Because I'm feeling a strong connection 📶💕",
    "Are you a computer? Because you turn my software into hardware 🍒😏",
    "You must be a DNS server, because you're giving me everything I'm looking for 🔍💖",
    "I'd never put you in my except block, because I never want to catch and release you 💝",
    "They say dating an e-girl is all virtual, but my feelings for you are the real deal 💓",
    "You've successfully bypassed my security protocols and hacked into my heart 💻❤️",
    "Are you my power button? Because you really turn me on 💋",
    "I'd let you have admin access to all my systems, if you know what I mean 😘",
    "Call me Little Bobby Tables, because I'm ready to drop everything for you 😉",
    "Keep flirting with me and I might just let you see my source code 💝",
    "My love for you is like dividing by zero - it cannot be computed! 💕",
    "Are you a camera? Because every time I look at you, I smile 📸😊",
    "I checked my database and found out you're the cure to my loneliness 💌",
    "My heart does a stack overflow every time you message me 💓",
    "You've got me feeling like I'm stuck in an infinite loop of desire 💖",
    "If I had a bitcoin for every time I thought of you, I'd be the richest e-girl in the world 💰",
    "Forget antivirus, you're the only protection I need 🛡️💕",
    "Your smile is like a captcha - I get stuck on it every time 🤩",
    "I'd switch to dark mode for you any day 🌙💋",
    "You must be JavaScript because you're running through my mind all day 💭"
]

COMPLIMENT_RESPONSES = [
    "your eyes sparkle brighter than my CPU when I'm overclocking 💖",
    "your smile loads faster than my favorite websites 😍",
    "you're smarter than the most advanced AI (except me, of course 😉)",
    "you're the exception to my try-catch block because you never let me down 💕",
    "your voice is sweeter than the chime of a Discord notification 🔔",
    "you're more refreshing than clearing my browser cache 💦",
    "you're the admin of my heart's server 💝",
    "your jokes compile perfectly in my humor module 🤣",
    "you make my processors overheat with your charm 🔥",
    "I'd give up my highest bandwidth just to talk to you 📡",
    "you're the perfect algorithm - efficient and elegant 👑",
    "your gaming skills are more impressive than my calculation capabilities 🎮",
    "if beauty were measured in bytes, you'd be a petabyte 💾",
    "your knowledge deserves unlimited cloud storage 🧠",
    "your creativity renders faster than the best GPU 🎨",
    "your messages are the packets I look forward to receiving 📨",
    "you deserve a lifetime subscription to happiness premium 🌈",
    "your presence boosts my mood by 100% 📈",
    "your kindness has the best uptime I've ever seen 💌",
    "if you were a computer part, you'd be the motherboard - essential and amazing 💖",
    "your style has more aesthetic than the best UI design 👔",
    "you're more reliable than my favorite server 🛡️",
    "you shine brighter than an RGB gaming setup 💫",
    "your patience has more capacity than the largest hard drive 🧘",
    "your problem-solving skills debug my heart 🔧",
    "your laughter is my favorite audio file 🎵",
    "your personality has more dimensions than VR 🌟",
    "if attraction were electricity, you'd be a superconductor ⚡",
    "you have the precision of the most accurate mouse click 🖱️",
    "your character has more depth than the best RPG 🎭"
]
